config/routes.rb
RogersFarmerrogersCom::Application.routes.draw do
  get "portfolio/index"

  get "connect/index"

  get "home/connect"

  get "home/portfolio"

  root :to => 'Home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/connect_controller.rb
class ConnectController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def connect
  end

  def portfolio
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connect_helper.rb
module ConnectHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/connect/index.html.erb
<ul class="connect_ul">
	<li id="email" class="connnect_li"><%= mail_to "rogers@farmerrogers.com", "Email Ben Rogers", :encode => "hex", :suject => "Website contact" %></li>

	<li id="phone" class="connnect_li">510.999.4720</li>

	<li id="repositories" class="connnect_li"><%= link_to "repositorites", "http://www.github.com/farmerrogers" %></li>

	<li id="twitter" class="connnect_li"><%= link_to "twitter", "http://www.twitter.com/farmerrogers" %></li>
</ul>

app/views/home/index.html.erb
<div id="msg_div">
	<p id="msg">I make for a living.</br></br>User experience based web sites & apps,</br>music, audio tech, stagecraft,</br>manual print, book-binding, and typography</br></br>are some of the things that I like to do and make,</br>since I do what I like for a living.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ben Rogers</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="all">
	<div id="line"></div>
  <div id="name_div">
	<h1 id="name"><%= link_to "Ben Rogers", root_path %></h1>
  </div>
  <ul class="nav_ul">
	<li id="connect" class="nav_li"><%= link_to "connect", connect_index_path %></li>
	<li id="portfolio" class="nav_li"><%= link_to "portfolio", portfolio_index_path %></li>
	<li id="resume" class="nav_li">resume.pdf</li>
  </ul>
  <div id="avatar_div">
	<figure id="avatar" class="image"><%= image_tag("hail.png", :alt => "A photo of the earnest worker, so that you might better know he exists.") %></figure>
  </div>

  <div id="specs_div">
		<figure id="specs" class="image"><%= image_tag("specs.jpg", :alt => "Gianni Versace MOD. 343") %></figure>
  </div>

<%= yield %>

</body>
</html>

app/views/portfolio/index.html.erb
<h1>Portfolio#index</h1>
<p>Find me in app/views/portfolio/index.html.erb</p>